# -*- coding: utf-8 -*-
"""Yasmin_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lafGXmggy01Ck-P8g_fpDx83P3vhH_jc
"""

import re

from collections import Counter

import matplotlib.pyplot as plt

def generate_histogram(file_path, N):
  #читаем файл
  with open(file_path, 'r', encoding="utf-8") as file:
    text = file.read()

  #clean and split text into words
  words = re.findall(r'\b\w+\b', text.lower())

  #count frequencies of each word
  word_counts = Counter(words)

  #get the N most common words
  common_words = word_counts.most_common(N)

  #gen the histogram
  words, counts = zip(*common_words)

  plt.figure(figsize=(20,6))
  plt.bar(words, counts, color='blue')
  plt.xlabel('Words')
  plt.ylabel('Frequencies')
  plt.title(f'Top {N} Most Frequent Words')
  plt.xticks(rotation=45, ha='right')
  plt.tight_layout()
  plt.show()

file_path = '/content/sample.txt'
N = 100

generate_histogram(file_path, N)